# Generated by Django 4.1.5 on 2023-08-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, max_length=50, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(choices=[('Diploma', 'دیپلم'), ('Bachelor', 'لیسانس'), ('Master', 'فوق لیسانس'), ('P.H.D', 'دکترا')], default='دکترا', max_length=50, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام و نام خانوادگی'),
        ),
    ]
