# Generated by Django 4.1.5 on 2023-08-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_phone_alter_teacher_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(choices=[('دیپلم', 'دیپلم'), ('لیسانس', 'لیسانس'), ('فوق لیسانس', 'فوق لیسانس'), ('دکترا', 'دکترا')], default='دکترا', max_length=50, verbose_name='مدرک تحصیلی'),
        ),
    ]
