# Generated by Django 4.1.5 on 2023-08-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_teacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(default='تهران', max_length=50, verbose_name=' شهر '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, max_length=50, verbose_name=' آدرس '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(choices=[('دیپلم', 'دیپلم'), ('لیسانس', 'لیسانس'), ('فوق لیسانس', 'فوق لیسانس'), ('دکترا', 'دکترا')], default='دکترا', max_length=50, verbose_name=' مدرک تحصیلی '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name=' نام و نام خانوادگی '),
        ),
    ]
