# Generated by Django 4.1.5 on 2023-08-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_city_city_alter_teacher_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.ForeignKey(default='تهران', on_delete=django.db.models.deletion.CASCADE, to='teacher.city'),
        ),
    ]
