# Generated by Django 4.1.5 on 2023-05-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='teacher',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
