# Generated by Django 4.1.5 on 2023-05-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_date_product_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reg_date',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
