# Generated by Django 4.1.5 on 2023-05-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, max_length=20000),
        ),
    ]
