# Generated by Django 4.1.5 on 2023-08-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_alter_teacher_city'),
        ('store', '0005_alter_product_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' تاریخ ایجاد '),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.TextField(blank=True, max_length=200, verbose_name=' تاریخ دوره '),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text=' ساعت ', max_length=500, verbose_name=' مدت زمان دوره'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, max_length=20000, verbose_name=' توضیحات '),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='photos/product', verbose_name=' تصویر '),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name=' فعال '),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name=' تاریخ آخرین تغیر '),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name=' قیمت '),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=2000, unique=True, verbose_name=' نام محصول '),
        ),
        migrations.AlterField(
            model_name='product',
            name='reg_date',
            field=models.TextField(blank=True, max_length=200, verbose_name=' مهلت ثبت نام '),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name=' ظرفیت '),
        ),
        migrations.AlterField(
            model_name='product',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
