# Generated by Django 4.1.5 on 2023-08-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_created_date_alter_product_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='teacher',
        ),
    ]
