# Generated by Django 4.1.5 on 2023-08-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='teacher',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
