# Generated by Django 4.1.5 on 2023-08-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='teacher',
        ),
    ]
