# Generated by Django 4.1.5 on 2023-08-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.IntegerField(blank=True, help_text=' ساعت ', max_length=500, verbose_name=' مدت زمان دوره'),
        ),
    ]
