# Generated by Django 4.1.5 on 2023-08-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_stockproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.IntegerField(blank=True, help_text=' ساعت ', verbose_name=' مدت زمان دوره'),
        ),
    ]
