# Generated by Django 4.1.5 on 2023-08-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(help_text=' تومان ', verbose_name=' قیمت '),
        ),
    ]
