# Generated by Django 4.1.5 on 2023-08-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_date_joined_alter_account_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' تاریخ ثبت نام '),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name=' ایمیل '),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name=' نام '),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' تاریخ آخرین ورود '),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name=' نام خانوادگی '),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name=' شماره موبایل '),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=10, unique=True, verbose_name=' نام کاربری '),
        ),
    ]
